[package]
name = "rmqtt"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive", "env"] }
dotenvy = { version = "0.15.7", features = ["clap"] }
futures-util = "0.3.32"
paho-mqtt = "0.14.0"
tokio = { version = "1.52.3", features = ["rt", "tokio-macros", "process", "full"] }
