
contact: https://github.com/kevinlutzer/rmqtt/issues
issues: https://github.com/kevinlutzer/rmqtt/issues
source-code: https://github.com/kevinlutzer/rmqtt
license: Apache-2.0-only
icon: snap/icons/icon.png

name: rmqtt
base: core24
version: '0.0.1' # Updated in the pipelines
summary: A rust based MQTT client 🦀
description: |
  This mqtt client can subscribe and publish to MQTT topics. For more
  information about the commands are arguments, run rmqtt --help.

grade: stable
confinement: strict 

plugs:
  rmqttconfig-file:
    interface: personal-files
    read:
    - $HOME/.rmqttconfig

apps:
  rmqtt: 
    command: bin/rmqtt
    plugs: [network, network-bind, rmqttconfig-file]

parts:
  rmqtt:
    build-packages: [libssl-dev, pkg-config, cmake, build-essential]
    plugin: rust
    source: .
