name: Build Lint and Test the Rust Application

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04-arm64

    steps:
    - uses: actions/checkout@v4

    - uses: extractions/setup-just@v3
      with:
        just-version: '1.40.0'
    
    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Format Check
      run: cargo fmt --check

    # Verify the cargo project can be built
    - name: Build
      run: cargo build

    # Build the snap
    - uses: snapcore/action-build@v1
